[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[project]
name = "mt-named-entity"
version = "0.1.0"
description = "Named entity handling for IS-EN MT systems"
authors = [{"name"= "Miðeind", "email"="tauganet@mideind.is"}]
readme = "README.md"
requires-python = "~=3.8"

dependencies= [
"nltk~=3.5",
"reynir~=2.10.1",
"transformers~=4.3.2",
"spacy~=2.0",
"pyjarowinkler~=1.8",
"scipy~=1.5",
"flair~=0.9",
"greynirseq @ git+https://github.com/mideind/greynirseq.git@d09e5b6e7030e94c78f3411e2e430f7af3732f14",
"islenska~=0.3.0",
]

[project.scripts]
mt = "mt_named_entity.cli:cli"


[project.optional-dependencies]
dev = [
"pytest~=6.0.1",
"rope~=0.17.0",
"black~=20.8b1",
"isort~=5.7.0",
"pylint~=2.7.2",
"flake8~=3.8.4",
"mypy~=0.812",
]
